// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails stimulus:controller

import { application } from "./application"

import ShareModalController from "./share_modal_controller"
application.register("share-modal", ShareModalController)

// Import and register Navbar and Theme controllers
import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

// Import and register dropdown controllers
import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import MobileDropdownController from "./mobile_dropdown_controller"
application.register("mobile-dropdown", MobileDropdownController)