// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails stimulus:controller

import { application } from "./application"

import ShareModalController from "./share_modal_controller"
application.register("share-modal", ShareModalController)

// Import and register Navbar and Theme controllers
import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

// Import and register dropdown controllers
import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HeaderDropdownController from "./header_dropdown_controller"
application.register("header-dropdown", HeaderDropdownController)

import SimpleDropdownController from "./simple_dropdown_controller"
application.register("simple-dropdown", SimpleDropdownController)

// Import and register admin controllers
import AdminSidebarController from "./admin_sidebar_controller"
application.register("admin-sidebar", AdminSidebarController)

import MobileDropdownController from "./mobile_dropdown_controller"
application.register("mobile-dropdown", MobileDropdownController)

// Import and register modal controller
import ModalController from "./modal_controller"
application.register("modal", ModalController)

// Import and register auto-dismiss controller
import AutoDismissController from "./auto_dismiss_controller"
application.register("auto-dismiss", AutoDismissController)

// Import and register parallax controller
import ParallaxController from "./parallax_controller"
application.register("parallax", ParallaxController)

// Import and register tabs controller
import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

// Import and register receive money controller
import ReceiveMoneyController from "./receive_money_controller"
application.register("receive-money", ReceiveMoneyController)

// Import and register icon controller
import IconController from "./icon_controller"
application.register("icon", IconController)

// Import and register theme mode controller
import ThemeModeController from "./theme_mode_controller"
application.register("theme-mode", ThemeModeController)

// Import and register avatar upload controller
import AvatarUploadController from "./avatar_upload_controller"
application.register("avatar-upload", AvatarUploadController)

// Import and register scroll header controller
import StickyHeaderController from "./sticky_header_controller"
application.register("scroll-header", StickyHeaderController)

// Import and register star rating controller
import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

// Import and register countdown controller
import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

// Import and register coupon controller
import CouponController from "./coupon_controller"
application.register("coupon", CouponController)

// Import and register coupon form controller
import CouponFormController from "./coupon_form_controller"
application.register("coupon-form", CouponFormController)

// Import and register sortable controller
import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

// Import and register product form controller
import ProductFormController from "./product_form_controller"
application.register("product-form", ProductFormController)

// Import and register product gallery controller
import ProductGalleryController from "./product_gallery_controller"
application.register("product-gallery", ProductGalleryController)

// Import and register product purchase controller
import ProductPurchaseController from "./product_purchase_controller"
application.register("product-purchase", ProductPurchaseController)

// Import and register sticky cart controller
import StickyCartController from "./sticky_cart_controller"
application.register("sticky-cart", StickyCartController)

// Import and register accordion controller
import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)