require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/event_categories", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EventCategory. As you add validations to EventCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EventCategory.create! valid_attributes
      get event_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      event_category = EventCategory.create! valid_attributes
      get event_category_url(event_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_event_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      event_category = EventCategory.create! valid_attributes
      get edit_event_category_url(event_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EventCategory" do
        expect {
          post event_categories_url, params: { event_category: valid_attributes }
        }.to change(EventCategory, :count).by(1)
      end

      it "redirects to the created event_category" do
        post event_categories_url, params: { event_category: valid_attributes }
        expect(response).to redirect_to(event_category_url(EventCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EventCategory" do
        expect {
          post event_categories_url, params: { event_category: invalid_attributes }
        }.to change(EventCategory, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post event_categories_url, params: { event_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_category" do
        event_category = EventCategory.create! valid_attributes
        patch event_category_url(event_category), params: { event_category: new_attributes }
        event_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the event_category" do
        event_category = EventCategory.create! valid_attributes
        patch event_category_url(event_category), params: { event_category: new_attributes }
        event_category.reload
        expect(response).to redirect_to(event_category_url(event_category))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        event_category = EventCategory.create! valid_attributes
        patch event_category_url(event_category), params: { event_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested event_category" do
      event_category = EventCategory.create! valid_attributes
      expect {
        delete event_category_url(event_category)
      }.to change(EventCategory, :count).by(-1)
    end

    it "redirects to the event_categories list" do
      event_category = EventCategory.create! valid_attributes
      delete event_category_url(event_category)
      expect(response).to redirect_to(event_categories_url)
    end
  end
end
