require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/event_comments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EventComment. As you add validations to EventComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EventComment.create! valid_attributes
      get event_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      event_comment = EventComment.create! valid_attributes
      get event_comment_url(event_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_event_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      event_comment = EventComment.create! valid_attributes
      get edit_event_comment_url(event_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EventComment" do
        expect {
          post event_comments_url, params: { event_comment: valid_attributes }
        }.to change(EventComment, :count).by(1)
      end

      it "redirects to the created event_comment" do
        post event_comments_url, params: { event_comment: valid_attributes }
        expect(response).to redirect_to(event_comment_url(EventComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EventComment" do
        expect {
          post event_comments_url, params: { event_comment: invalid_attributes }
        }.to change(EventComment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post event_comments_url, params: { event_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_comment" do
        event_comment = EventComment.create! valid_attributes
        patch event_comment_url(event_comment), params: { event_comment: new_attributes }
        event_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the event_comment" do
        event_comment = EventComment.create! valid_attributes
        patch event_comment_url(event_comment), params: { event_comment: new_attributes }
        event_comment.reload
        expect(response).to redirect_to(event_comment_url(event_comment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        event_comment = EventComment.create! valid_attributes
        patch event_comment_url(event_comment), params: { event_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested event_comment" do
      event_comment = EventComment.create! valid_attributes
      expect {
        delete event_comment_url(event_comment)
      }.to change(EventComment, :count).by(-1)
    end

    it "redirects to the event_comments list" do
      event_comment = EventComment.create! valid_attributes
      delete event_comment_url(event_comment)
      expect(response).to redirect_to(event_comments_url)
    end
  end
end
